export const ACCOUNTING = 'accounting'
export const FINANCIAL_OPERATIONS = 'financial-operations'
export const CALLS = 'calls'
export const PHONE_NUMBERS = 'phone-numbers'
export const OPERATOR_PROFILES = 'operator-profiles'
export const BLOCKED_PHONE_NUMBERS = 'blocked-phone-numbers'
export const CALL_EXTENSIONS = 'call-extensions'
export const COMPANY_DIAL_NUMBERS = 'company-dial-numbers'
export const GENERAL_PERMISSION_SYSTEM = 'general-permission-system'
export const PROJECTS = 'projects'
export const DIRECTIONS = 'directions'
export const TASKS = 'tasks'
export const WORKER_PROFILES = 'worker-profiles'
export const WORK_TIME_RANGES = 'work-time-ranges'
export const DOCUMENTS = 'documents'
export const CUSTOMER_COMPANIES = 'customer-companies'
export const OUR_COMPANIES = 'our-companies'
export const CUSTOMER_PROFILES = 'customer-profiles'
/** @deprecated use CUSTOMER_COMPANIES — kept for existing links */
export const CUSTOMERS = CUSTOMER_COMPANIES
export const APPEALS = 'appeals'
export const SUPPORT = 'support'
export const APPLICATIONS_FROM_WEBSITE = 'applications-from-website'
export const SYSTEM_USERS = 'users'

export const COMMON_CREATING = 'create'
export const COMMON_EDITING = 'edit'
