export const ACCOUNTING = 'accounting'
export const BUDGET = 'budget'
export const CALL_HISTORY = 'call-history'
export const GENERAL_PERMISSION_SYSTEM = 'general-permission-system'
export const PROJECTS = 'projects'
export const TASKS = 'tasks'
export const DOCUMENTS = 'documents'
export const CUSTOMERS = 'customers'
export const APPEALS = 'appeals'
export const SUPPORT = 'support'
export const APPLICATIONS_FROM_WEBSITE = 'applications-from-website'
export const EMPLOYEES = 'employees'

export const COMMON_CREATING = 'create'
export const COMMON_EDITING = 'edit'
